<?php

require_once("logging.php");
require_once("html.php");

create_html_start("Lähteet");

echo "<b>Alkuperäiset asiakirjalähteet:</b><br><br>\n";
echo "Alatornion rippikirjat 1800-1900<br>\n";
echo "Haapajärven rippikirjat 1827-1900<br>\n";
echo "Haapaveden rippikirjat 1712-1839, 1862-1869<br>\n";
echo "Hailuodon rippikirjat 1891-1900<br>\n";
echo "Halsuan rippikirjat 1864-1898<br>\n";
echo "Haukiputaan rippikirjat 1790-1900<br>\n";
echo "Helsingin rippikirjat 1870-1881<br>\n";
echo "Hyrynsalmen rippikirjat 1786-1865<br>\n";
echo "Iin rippikirjat 1714-1920<br>\n";
echo "Inarin rippikirjat 1843-1868<br>\n";
echo "Jäppilän rippikirjat 1877-1919<br>\n";
echo "Kajaanin rippikirjat 1790-1847<br>\n";
echo "Kalajoen rippikirjat 1806-1874<br>\n";
echo "Karungin rippikirjat 1838-1900<br>\n";
echo "Kemin rippikirjat 1693-1920<br>\n";
echo "Kemijärven rippikirjat 1698-1900<br>\n";
echo "Kempeleen rippikirjat 1734-1899<br>\n";
echo "Kiimingin rippikirjat 1822-1895<br>\n";
echo "Kittilän rippikirjat 1790-1900<br>\n";
echo "Kiuruveden rippikirjat 1819-1920<br>\n";
echo "Kivennavan rippikirjat 1900-1919<br>\n";
echo "Kuivaniemen rippikirjat 1823-1900<br>\n";
echo "Kurikan rippikirjat 1736-1912<br>\n";
echo "Kuusamon rippikirjat 1760-1773, 1798-1895<br>\n";
echo "Limingan rippikirjat 1738-1900<br>\n";
echo "Lumijoen rippikirjat 1901-1920<br>\n";
echo "Merijärven rippikirjat 1818-1845<br>\n";
echo "Muhoksen rippikirjat 1757-1901<br>\n";
echo "Nivalan rippikirjat 1832-1900<br>\n";
echo "Oulaisten rippikirjat 1758-1910<br>\n";
echo "Oulun rippikirjat 1742-1900<br>\n";
echo "Oulujoen rippikirjat 1844-1900<br>\n";
echo "Oulunsalon rippikirjat 1748-1900<br>\n";
echo "Paavolan rippikirjat 1781-1900<br>\n";
echo "Paltamon rippikirjat 1731-1910<br>\n";
echo "Pattijoen rippikirjat 1854-1900<br>\n";
echo "Pieksämäen rippikirjat 1757-1899<br>\n";
echo "Pudasjärven rippikirjat 1700, 1714, 1723-1920<br>\n";
echo "Puolangan rippikirjat 1797-1810<br>\n";
echo "Rantsilan rippikirjat 1860-1870<br>\n";
echo "Reisjärven rippikirjat 1813-1846<br>\n";
echo "Revonlahden rippikirjat 1805-1900<br>\n";
echo "Ristijärven rippikirjat 1807-1910<br>\n";
echo "Rovaniemen rippikirjat 1742-1920<br>\n";
echo "Sallan rippikirjat 1832-1900<br>\n";
echo "Saloisten rippikirjat 1891-1900<br>\n";
echo "Siikajoen rippikirjat 1798-1900<br>\n";
echo "Simon rippikirjat 1791-1920<br>\n";
echo "Sodankylän rippikirjat 1731-1910<br>\n";
echo "Suomussalmen rippikirjat 1787-1900<br>\n";
echo "Suonenjoen rippikirjat 1824-1869<br>\n";
echo "Taivalkosken rippikirjat 1874-1900<br>\n";
echo "Tampereen rippikirjat 1888-1907<br>\n";
echo "Temmeksen rippikirjat 1802-1900<br>\n";
echo "Tervolan rippikirjat 1693-1920<br>\n";
echo "Toholammen rippikirjat 1774-1899<br>\n";
echo "Tornion rippikirjat 1839-1900<br>\n";
echo "Turtolan rippikirjat 1881-1890<br>\n";
echo "Tyrnävän rippikirjat 1832-1900<br>\n";
echo "Utajärven rippikirjat 1775-1910<br>\n";
echo "Vihannin rippikirjat 1801-1900<br>\n";
echo "Viitasaaren rippikirjat 1866-1900<br>\n";
echo "Ylikiimingin rippikirjat 1764-1900<br>\n";
echo "Ylitornion rippikirjat 1820-1920<br>\n";
echo "Ylivieskan rippikirjat 1891-1900<br><br>\n";
echo "<b>Kirjalliset lähteet:</b><br><br>\n";
echo "98995 Kylä napapiirillä<br>\n";
echo "Aikion suku Kemijärvellä ja Posiolla<br>\n";
echo "Aikkian pojat ja tyttäret<br>\n";
echo "Antti Kurtti Kuusamosta... ja hänen sukunsa<br>\n";
echo "Atimoja - Kelloselän ja Aatsingin kyläkirja<br>\n";
echo "Elämäntarinoita Kemijärveltä<br>\n";
echo "Esivanhempien kautta tutuksi Lars Tauriainen s. 1600 jälkeläisiä<br>\n";
echo "Haavikon suku 1665-2010<br>\n";
echo "Hanheloita kolmen vuosisadan ajalta<br>\n";
echo "Henrik Kurtti-Kivilahden suku vuosina 1660-1992<br>\n";
echo "Ihmisen aika<br>\n";
echo "Iin veteraanimatrikkeli<br>\n";
echo "Inarin Kyröistä<br>\n";
echo "Isäin tietä astumassa - Oulaisten veteraanimatrikkeli<br>\n";
echo "Isänmaan vapauden puolesta - Kemijärven veteraanimatrikkeli<br>\n";
echo "Itkosten suku III<br>\n";
echo "Johan Korolaisen jälkeläiset<br>\n";
echo "Juho Juhonpojan jälkeläiset<br>\n";
echo "Jumisko suku 1783 alkaen<br>\n";
echo "Juuret Jurvasenkuivalla<br>\n";
echo "Jöran Jöranin pojasta vuosisatojen saatossa nykypäivään<br>\n";
echo "Kaasilan sukukirja<br>\n";
echo "Kaavin Räsäsiä<br>\n";
echo "Kaheksan Eerikkiä ja emänät<br>\n";
echo "Kainuun Moilaskansa<br>\n";
echo "Kalaojan sukukirja<br>\n";
echo "Kelan suku<br>\n";
echo "Kemppaiset Kainuusta<br>\n";
echo "Kiannon huori poika<br>\n";
echo "Knihtijääkärikorpaali Esaias Granrothin jälkeläisiä - Alakurtin sukua<br>\n";
echo "Kolmen rintaman veteraanit - Sallan veteraanimatrikkeli<br>\n";
echo "Koti Kynsijärvellä<br>\n";
echo "Kuhmitsan sukua - Johan Matinpoika Kairalan jälkeläiset<br>\n";
echo "Kuolajärven kylä - Pakkoluovutettu<br>\n";
echo "Kurikan Paulaharjut<br>\n";
echo "Kurola > Aunola Johan Erikinp. Kurolan jälkeläisiä<br>\n";
echo "Kuusamon Haatajat suku 2. painos<br>\n";
echo "Kuusamon Leinoset<br>\n";
echo "Kuusamon Saapungit ja heidän jälkeläisensä<br>\n";
echo "Kuusamon Veteläiset<br>\n";
echo "Kylä vaarojen kainalossa<br>\n";
echo "Lautamies Eric Påhlinpoika Hukan eli Kukan 1698-1770 suku ja sukulaiset<br>\n";
echo "Liminkalaisen talonpoika Heikki Matinpoika Tuorilan (1649) jälkeläisiä<br>\n";
echo "Luettelo Filip Tuomaanpoika Pätsin s. 1658 suvun jäsenistä<br>\n";
echo "Luettelo Kallunki-Pitkä suvun jäsenistä<br>\n";
echo "Matinlompolon sukukirja<br>\n";
echo "Me Sompiosta<br>\n";
echo "Meidän kylämme Kuukasjärvi<br>\n";
echo "Mourujärvi - Kylä ja ihmiset<br>\n";
echo "Ne niemet ja vaarat - Pudasjärven ja Taivalkosken Parviaisten sukua<br>\n";
echo "Nils Petter Tiuraniemen esisukupolvia ja jälkeläisiä<br>\n";
echo "Niskajärven ervastit<br>\n";
echo "Nyynäjän tarina - Poroputaan suku Pudasjärvellä<br>\n";
echo "Oikarisia neljältä vuosisadalta<br>\n";
echo "Oulun sukututkija 1995:01<br>\n";
echo "Paanajärven Paloniemet<br>\n";
echo "Pattijoen Ylipään Pekkalat<br>\n";
echo "Pekan poikia ja tyttäriä<br>\n";
echo "Pelkosenniemeläiset isänmaan puolustajina - Pelkosenniemen veteraanimatrikkeli<br>\n";
echo "Petter Hällströmin suku<br>\n";
echo "Pielaveden Niemisjärven (Laukkanen) Tikkaset<br>\n";
echo "Pirttilän pirtistä maailmalle - Pirttilän suvun vaiheet ajan saatossa<br>\n";
echo "Pohjois-Suomen Kähkösiä ja Keckmaneja<br>\n";
echo "Poikela, Äärelä ja sen sata sivusukua<br>\n";
echo "Pudasjärven Ojaloita - Vuodesta 1548 nykypäivään<br>\n";
echo "Päiväniemen suku - Sotkamosta Kuusamon kautta Sovajärvelle<br>\n";
echo "Pöykkölästä maailmalle<br>\n";
echo "Ryti-Lehtolan kyläkirja<br>\n";
echo "Savon halosista lapin aikiohin ja olliloihin<br>\n";
echo "Savukosken veteraanimatrikkeli<br>\n";
echo "Siikajoen Meriläiset<br>\n";
echo "Simo Määttä-Suorajärven sukuhaara<br>\n";
echo "Sippo Laurinpoika Raasakan jälkeläiset<br>\n";
echo "Sodankylän veteraanimatrikkeli<br>\n";
echo "Sotkamon lukkarit<br>\n";
echo "Sukukertomus<br>\n";
echo "Sukuselvityksen kohde Antti Antinpoika Hyttinen s. 24.5.1721 Pudasjärvi Kollaja<br>\n";
echo "Sukuselvityksen kohde Olof Ollinpoika Ingerö s. 23.11.1748 Rovaniemi Autti<br>\n";
echo "Sukuselvityksen kohde Pehr Antinpoika Saarijärvi s. 1728 Pudasjärvi<br>\n";
echo "Sukuselvityksen kohde Pekka Antinpoika Ruokamo s. 25.9.1746 Kuusamo<br>\n";
echo "Sukuselvityksen kohde Sigfrid Johanpoika Ronkainen s. 4.2.1775 Kuusamo<br>\n";
echo "Sukuselvityksen kohde Simon Simonpoika Määttä, Salminen s. 1712 Kuusamo<br>\n";
echo "Sulasalmi-Impola sukukirja<br>\n";
echo "Sulkavalla asuneen Antti Keräsen jälkeläiset<br>\n";
echo "Suomen metsurit<br>\n";
echo "Suomen rintamamiehet 1939 -  1945 - 6. Div<br>\n";
echo "Suomuvuoman suomalaiset<br>\n";
echo "Suuri Maatilakirja VII<br>\n";
echo "Tapion sukuselvitys<br>\n";
echo "Tervjärv-Kemijärvi 1944-1945<br>\n";
echo "Tuntsan kojamot<br>\n";
echo "Törmäsillä<br>\n";
echo "Uudisraivaajia runsailla riistamailla<br>\n";
echo "Vaalajärvi - metsälappalaisten Pumpanen<br>\n";
echo "Vallesmannin perilliset<br>\n";
echo "Väyrysmiitti<br>\n";
echo "Ylipaakkola - Meän kylä kahen puolin jokia<br>\n";
echo "<br><br>";

echo "<form action=\"main.php\" method=\"post\">\n";
echo " <input type=\"submit\" name=\"return_from_source\" value=\"Palaa takaisin\">\n";
echo "</form>\n";

create_html_end();

?>